config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :reserves do
    resources :soldiers do
      resources :loans do
        get :give_back_all_weapons
        get :give_back_all_munitions
        get :give_back_all_accessories
        resources :loan_weapons
        resources :loan_weapon_logs
        resources :loan_munition_logs
        resources :loan_munitions
        resources :loan_accessory_logs
        resources :loan_accessories
      end
    end
    
    resources :garrisons do
      resources :accessories
      resources :munitions
      resources :weapons
    end
  end
  

end

app/models/loan_munition.rb
class LoanMunition < ActiveRecord::Base
	validates :amount, presence: true, numericality: { only_integer: true, :greater_than_or_equal_to => 1}
  belongs_to :loan
  belongs_to :munition
  belongs_to :reserve
end

app/controllers/loan_munitions_controller.rb
class LoanMunitionsController < ApplicationController
  before_action :set_loan_munition, only: [:edit, :update, :destroy]

  # GET /loan_munitions/new
  def new
    @reserve = Reserve.where(id: params[:reserf_id]).first
    @soldier = Soldier.find(params[:soldier_id])
    @loan = Loan.find(params[:loan_id])
    if !@loan.active
      respond_to do |format|
        format.html { redirect_to reserf_soldier_loans_path(@reserve,@soldier), notice: 'Cautela já encerrada, inicie uma nova cautela' }
        format.json { head :no_content }
      end
    end
    
    @loan_munition = @loan.loan_munitions.build

    @munitions = Munition.where(garrison: @reserve.garrison).where.not("amount <= ?",0)
  end

  # GET /loan_munitions/1/edit
  def edit
  end

  # POST /loan_munitions
  # POST /loan_munitions.json
  def create
    @reserve = Reserve.where(id: params[:reserf_id]).first
    @soldier = Soldier.find(params[:soldier_id])
    @loan = Loan.find(params[:loan_id])
    
    @loan_munition = @loan.loan_munitions.build(loan_munition_params)
    @loan_munition.loan = @loan
    @loan_munition.reserve = @reserve

    @loan_munition_log = @loan.loan_munition_logs.build(loan_munition_params)
    @loan_munition_log.loan = @loan
    @loan_munition_log.reserve = @reserve

    respond_to do |format|
      if !@loan_munition.amount.nil? and !@loan_munition.munition.nil?
        @munition = Munition.find(@loan_munition.munition)
        if @munition.amount >= @loan_munition.amount
          @munition.amount -= @loan_munition.amount
          if @loan_munition.save and @munition.save and @loan_munition_log.save
            format.html { redirect_to reserf_soldier_loan_path(@reserve,@soldier,@loan), notice: 'Loan munition was successfully created.' }
            format.json { render :show, status: :created, location: reserf_soldier_loan_path(@reserve,@soldier,@loan) }
          else
            format.html { render :new }
            format.json { render json: @loan_munition.errors, status: :unprocessable_entity }
          end
        else
          format.html { redirect_to new_reserf_soldier_loan_loan_munition_path(@reserve,@soldier,@loan), notice: 'Só se pode pegar até a quantidade que tem na Reserva' }
          format.json { render :show, status: :created, location: reserf_soldier_loan_loan_munition_path(@reserve,@soldier,@loan) }
        end
      else
        format.html { redirect_to new_reserf_soldier_loan_loan_munition_path(@reserve,@soldier,@loan), notice: 'É necessario ter uma quantidade e escolher a munição' }
        format.json { render :show, status: :created, location: reserf_soldier_loan_loan_munition_path(@reserve,@soldier,@loan) }
      end
    end
  end

  # PATCH/PUT /loan_munitions/1
  # PATCH/PUT /loan_munitions/1.json
  def update
    respond_to do |format|
      if @loan_munition.update(loan_munition_params)
        format.html { redirect_to reserf_soldier_loan_path(@reserve,@soldier,@loan), notice: 'Loan munition was successfully updated.' }
        format.json { render :show, status: :ok, location: reserf_soldier_loan_path(@reserve,@soldier,@loan) }
      else
        format.html { render :edit }
        format.json { render json: @loan_munition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loan_munitions/1
  # DELETE /loan_munitions/1.json
  def destroy
    @munition = Munition.find(@loan_munition.munition)
    @munition.amount += @loan_munition.amount
    @munition.save
    @loan_munition.destroy
    respond_to do |format|
      format.html { redirect_to reserf_soldier_loan_path(@reserve,@soldier,@loan), notice: 'Loan munition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loan_munition
      @reserve = Reserve.where(id: params[:reserf_id]).first
      @soldier = Soldier.find(params[:soldier_id])
      @loan = Loan.find(params[:loan_id])
      @loan_munition = LoanMunition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def loan_munition_params
      params.require(:loan_munition).permit(:munition_id, :amount)
    end
end

app/helpers/loan_munitions_helper.rb
module LoanMunitionsHelper
end

app/views/loan_munitions/_form.html.erb
<p id="notice" class="text-md-center"><%= notice %></p>
<%= form_for([@reserve,@soldier,@loan,@loan_munition]) do |f| %>
  <% if @loan_munition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@loan_munition.errors.count, "error") %> prohibited this loan_munition from being saved:</h2>

      <ul>
      <% @loan_munition.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="text-md-center">
    <strong>Quantidade a ser retirada: </strong><br>
    <%= f.number_field :amount %>
  </div>
  </br>
  <div class="new-form">
    <% @munitions.each do |munition|%>
        <p><%= f.radio_button :munition_id, munition.id %><strong>Calibre: </strong><%= munition.caliber %></p>
        <p><strong>Descrição: </strong><%= munition.description %></p>
        <p><strong>Quantidade: </strong><%= munition.amount %></p>
        <hr>
    <% end %>
  <div class="actions">
     <%= f.submit "OK", :type => "submit" , :class => "btn btn-primary" %>
  </div>
<% end %>
  </div>

app/views/loan_munitions/edit.html.erb
<header class="header-reserva">
  <h1>Editando Munição na Cautela</h1>
</header>

<%= render 'form' %>

<%= link_to 'Show', @loan_munition %> |
<%= link_to 'Back', loan_munitions_path %>

app/views/loan_munitions/new.html.erb
<header class="header-reserva">
  <h1>Nova Munição na Cautela</h1>
</header>

<%= render 'form' %>